#!/usr/bin/env bash

set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

# 0.1: Custom plugin to remove the bridge network from a specific container after the build

APP_NAME=$1
CONTAINER_ID=$2

echo "-----> Plugin: Proxy patcher"

# Check if container ID is provided
if [ -z "$CONTAINER_ID" ]; then
  echo "       $APP_NAME container not found. Skipping bridge removal."
  exit 0
fi

# Check if container is connected to the bridge network and disconnect if so
network_mode=$(docker inspect --format '{{.HostConfig.NetworkMode}}' "$CONTAINER_ID")

if [ "$network_mode" == "bridge" ]; then
  echo "       Removing bridge network from $APP_NAME so proxy doesn't get confused"
  docker network disconnect bridge "$CONTAINER_ID" || true
else
  echo "       $APP_NAME is already disconnected from the bridge network."
fi